In [27]:
import pandas as pd
excel_filename = "Extended_Dataset_with_predictions.csv"
prediction_column = "ChatGPT 4o prediction GLAD"
if excel_filename.endswith(".csv"):
    df = pd.read_csv(excel_filename)
else:
    df = pd.read_excel(excel_filename)
df.dropna(inplace=True)

df = df[df[prediction_column].apply(lambda x: "na" not in x and "NA" not in x)]

df.head()

,Image number,Image File name,Item in image,True item Location,Annotator,Is In Picture,ChatGPT 4o prediction GLAD
0,0,IMAGE_000.jpg,Blue recycling bin,"center, center, far",Zach,Yes,center bottom far
2,2,IMAGE_001.jpg,Black cup,"left, bottom, medium",Zach,Yes,left bottom near
4,4,IMAGE_002.jpg,Crock sandal,"center, center, medium",Zach,Yes,center center near
6,6,IMAGE_003.jpg,Amazon box,"center, center, close",Zach,Yes,center center near
7,7,IMAGE_004.jpg,Basketball,"center, center, medium",Zach,Yes,right bottom near

In [28]:
import string

# Remove punctuation from the 'True item Location' column
df['True item  Location'] = df['True item  Location'].str.replace(f"[{string.punctuation}]", "", regex=True)
df.head()

,Image number,Image File name,Item in image,True item Location,Annotator,Is In Picture,ChatGPT 4o prediction GLAD
0,0,IMAGE_000.jpg,Blue recycling bin,center center far,Zach,Yes,center bottom far
2,2,IMAGE_001.jpg,Black cup,left bottom medium,Zach,Yes,left bottom near
4,4,IMAGE_002.jpg,Crock sandal,center center medium,Zach,Yes,center center near
6,6,IMAGE_003.jpg,Amazon box,center center close,Zach,Yes,center center near
7,7,IMAGE_004.jpg,Basketball,center center medium,Zach,Yes,right bottom near

In [29]:
df["True item  Location"].unique()

array(['center center far', 'left bottom medium', 'center center medium',
       'center center close', 'right top close', 'right top medium',
       'left top medium', 'top right far', 'left center medium',
       'left center far', 'center top medium', 'center top close',
       'center top far', 'right center far', 'right center medium',
       'right bottom medium', 'left bottom close', 'left center close',
       'center bottom medium', 'left bottom far', 'right center near',
       'left bottom close ', 'right bottom close', 'center center near',
       'center center  far', 'left top far', 'centercenter medium',
       'right bottom far', 'left center near', 'right bottom near',
       'right center  medium', 'centerbottom far', 'left bottom near',
       'right center mediun', 'center center close '], dtype=object)

In [30]:
df[df["True item  Location"].apply(lambda x: len(x.split())) == 2]

,Image number,Image File name,Item in image,True item Location,Annotator,Is In Picture,ChatGPT 4o prediction GLAD
105,105,IMAGE_083.jpg,Knife,centercenter medium,Ayan,Yes,center center medium
129,129,IMAGE_100.jpg,Welsh Flag,centerbottom far,Ayan,Yes,center top medium

In [26]:
df["LR_True"] = df["True item  Location"].apply(lambda x: x.split(" ")[0])
df["UD_True"] = df["True item  Location"].apply(lambda x: x.split(" ")[1])
df["FN_True"] = df["True item  Location"].apply(lambda x: x.split(" ")[2])

def recast_close_to_near(x):
    if x == 'close':
        return 'near'
    else:
        return x

df["FN_True"] = df["FN_True"].apply(lambda x: recast_close_to_near(x))

df["LR_Pred"] = df[prediction_column].apply(lambda x: x.split()[0])
df["UD_Pred"] = df[prediction_column].apply(lambda x: x.split()[1])
df["FN_Pred"] = df[prediction_column].apply(lambda x: x.split()[2])

accuracy_LR = (df["LR_True"] == df["LR_Pred"]).mean()
accuracy_UD = (df["UD_True"] == df["UD_Pred"]).mean()
accuracy_FN = (df["FN_True"] == df["FN_Pred"]).mean()

print(f"Accuracy for LR: {accuracy_LR}")
print(f"Accuracy for UD: {accuracy_UD}")
print(f"Accuracy for FN: {accuracy_FN}")

Accuracy for LR: 0.6623376623376623
Accuracy for UD: 0.2662337662337662
Accuracy for FN: 0.2727272727272727